### ISSUE TITLE
No HEX support with Text Displays

### ISSUE THREAD

**Issue by EarthAgar** [56738/EasyArmorStands#1]
When testing out the plugin with MiniMessage formatting I don't get any hex colors that function. I don't know if these entities just don't support it or there is an oversight but I just know that I can't set gradients or custom colors for the text of a display entity.

Below is an example of what the chat shows the text should look like and what the text on the entity looks like.
![image](https://github.com/56738/EasyArmorStands/assets/27425322/d820467a-5c4c-45e2-a9ef-408c4d9a80aa)

**Comment by 56738** [comment]
What server software are you running? Text displays currently only support hex colors on [Paper](https://papermc.io/software/paper).
