### ISSUE TITLE
TextDisplay will not work

### ISSUE THREAD

**Issue by Brammie260** [56738/EasyArmorStands#10]
Hi there, If i want to add a text display it will not do it. I tried version 2.0.1, 2.0.2 and 2.0.3 and nothing will work. On version 2.0.1 i get this error. same at every version i thought.
![easerrortextdisplay](https://github.com/56738/EasyArmorStands/assets/16277770/051728a2-8470-41c6-ba64-35f6ded2bb14)

We run on 1.20.1 Spigot. Error was taken from version 2.0.1 and this is de debug results:
![image](https://github.com/56738/EasyArmorStands/assets/16277770/e53bb4df-76c6-4cd8-9c59-d27d58597200)
![image](https://github.com/56738/EasyArmorStands/assets/16277770/2fd86260-172f-4b51-97e5-27c836cb8555)
The armor stand ticking could that be the issue?

**Comment by 56738** [comment]
This was fixed two months ago, but apparently I forgot to release a new version with that fix.
You can use the latest snapshot build for now: https://hangar.papermc.io/56738/EasyArmorStands/versions

**Comment by 56738** [comment]
Released v2.1.0 with 1.20.6 support and a fix for this.
https://hangar.papermc.io/56738/EasyArmorStands/versions/2.1.0
