### ISSUE TITLE
support air item type

### ISSUE THREAD

**Issue by qaz197418i** [56738/EasyArmorStands#6]
I want the menu-background in the menu to not display anything, but I tried to change it to air and it won't work properly
![image](https://github.com/56738/EasyArmorStands/assets/30312760/b08f7a84-164d-462d-a9e3-ccc078651314)

**Comment by 56738** [comment]
Fixed in v2.0.1 (f62acee1aa04fd24e07be4f0cbbfc6656eb72e35), but that's not released yet, you can use [this snapshot build](https://hangar.papermc.io/56738/EasyArmorStands/versions/2.0.1-SNAPSHOT+85) for now. Thanks!
